# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-11-18 02:31
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DialogueInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiveTime', models.DateTimeField(verbose_name='接收时间')),
                ('receiveContent', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='接收内容')),
                ('sendTime', models.DateTimeField(auto_now_add=True, verbose_name='处理时间')),
                ('sendContent', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='处理内容')),
            ],
        ),
        migrations.CreateModel(
            name='Express',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='快递', max_length=128, verbose_name='快递名称')),
                ('alias', models.CharField(help_text='别名', max_length=32, verbose_name='别名')),
            ],
        ),
        migrations.CreateModel(
            name='ParseStation',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('station', models.CharField(db_index=True, max_length=32)),
                ('alias', models.CharField(max_length=12)),
                ('fullPingyi', models.CharField(db_index=True, max_length=32)),
                ('firstfight', models.CharField(db_index=True, max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openid', models.CharField(max_length=128, verbose_name='微信号')),
                ('country', models.CharField(blank=True, max_length=36, verbose_name='国家')),
                ('language', models.CharField(blank=True, max_length=36, verbose_name='语言')),
                ('province', models.CharField(blank=True, max_length=36, verbose_name='省')),
                ('city', models.CharField(blank=True, max_length=128, verbose_name='城市')),
                ('subscribe', models.IntegerField(choices=[(1, '已关注'), (2, '未关注')], verbose_name='是否关注')),
                ('subscribe_time', models.DateTimeField(blank=True, verbose_name='关注时间')),
                ('groupid', models.IntegerField(blank=True, verbose_name='分组id')),
                ('sex', models.IntegerField(choices=[(1, '男'), (2, '女')], verbose_name='性别')),
                ('nickname', models.CharField(blank=True, max_length=128, verbose_name='别名')),
                ('remark', models.CharField(blank=True, max_length=128, verbose_name='备注')),
                ('headimgurl', models.CharField(blank=True, max_length=256, verbose_name='用户头像')),
            ],
        ),
        migrations.CreateModel(
            name='UserLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Latitude', models.CharField(max_length=12, verbose_name='纬度')),
                ('Longitude', models.CharField(max_length=12, verbose_name='经度')),
                ('createTime', models.DateTimeField(auto_now_add=True, verbose_name='时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weixin.UserInfo')),
            ],
        ),
        migrations.AddField(
            model_name='dialogueinformation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weixin.UserInfo'),
        ),
    ]
