# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-11-18 01:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180424_2227'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='flag',
            field=models.IntegerField(choices=[(1, '显示'), (2, '隐藏')], default=1, verbose_name='标记'),
            preserve_default=False,
        ),
    ]
